image: ubuntu:20.04

stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive # required for submodules
  DEBIAN_FRONTEND: noninteractive

cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
    policy: pull-push

deploy-apps:
  only:
    - /^v(\d+)\.(\d+)\.(\d+)(\.[a-z]+)?$/
  stage: deploy
  before_script:
    - apt update && apt install -yq nodejs npm curl rsync ssh
    - npm install -g n
    - n latest
    # we purge the old NodeJS version
    - apt purge -yq nodejs npm
    # we update the path to ensure the new NodeJS version is being used
    - PATH=$PATH
    - cd app
    - npm ci
  script:
    # we build the production app
    - npm run-script make
    # we move in the production settings...
    - rm build/web/settings.json && mv build/web/settings_prod.json build/web/settings.json
    # we store the commit SHA (so that the frontend can ask for a reload)
    - sed -i -e "s/COMMIT_SHA/${CI_COMMIT_SHA}/g" build/web/settings.json
    # now deploy everything in the "build/web" directory to the CDN